// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cyancyan2020/iam-platform/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// OperationLogRepository is an autogenerated mock type for the OperationLogRepository type
type OperationLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, log
func (_m *OperationLogRepository) Create(ctx context.Context, log *model.OperationLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OperationLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Query provides a mock function with given fields: ctx, start, end, offset, limit
func (_m *OperationLogRepository) Query(ctx context.Context, start time.Time, end time.Time, offset int, limit int) ([]model.OperationLog, int64, error) {
	ret := _m.Called(ctx, start, end, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []model.OperationLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]model.OperationLog, int64, error)); ok {
		return rf(ctx, start, end, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []model.OperationLog); ok {
		r0 = rf(ctx, start, end, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OperationLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) int64); ok {
		r1 = rf(ctx, start, end, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r2 = rf(ctx, start, end, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewOperationLogRepository creates a new instance of OperationLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationLogRepository {
	mock := &OperationLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
