// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PermissionRepository is an autogenerated mock type for the PermissionRepository type
type PermissionRepository struct {
	mock.Mock
}

// HasPermission provides a mock function with given fields: ctx, userID, path, method
func (_m *PermissionRepository) HasPermission(ctx context.Context, userID uint64, path string, method string) (bool, error) {
	ret := _m.Called(ctx, userID, path, method)

	if len(ret) == 0 {
		panic("no return value specified for HasPermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, string) (bool, error)); ok {
		return rf(ctx, userID, path, method)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string, string) bool); ok {
		r0 = rf(ctx, userID, path, method)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, string, string) error); ok {
		r1 = rf(ctx, userID, path, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPermissionRepository creates a new instance of PermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionRepository {
	mock := &PermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
