// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cyancyan2020/iam-platform/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// RolePermissionRepository is an autogenerated mock type for the RolePermissionRepository type
type RolePermissionRepository struct {
	mock.Mock
}

// BatchReplace provides a mock function with given fields: ctx, roleID, permIDs
func (_m *RolePermissionRepository) BatchReplace(ctx context.Context, roleID uint64, permIDs []uint64) error {
	ret := _m.Called(ctx, roleID, permIDs)

	if len(ret) == 0 {
		panic("no return value specified for BatchReplace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []uint64) error); ok {
		r0 = rf(ctx, roleID, permIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByRoleID provides a mock function with given fields: ctx, roleID
func (_m *RolePermissionRepository) FindByRoleID(ctx context.Context, roleID uint64) ([]model.RolePermission, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoleID")
	}

	var r0 []model.RolePermission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]model.RolePermission, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []model.RolePermission); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RolePermission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRolePermissionRepository creates a new instance of RolePermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRolePermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RolePermissionRepository {
	mock := &RolePermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
