// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/cyancyan2020/iam-platform/internal/handler"
	"github.com/cyancyan2020/iam-platform/internal/middleware"
	"github.com/cyancyan2020/iam-platform/internal/model"
	"github.com/cyancyan2020/iam-platform/internal/repository"
	"github.com/cyancyan2020/iam-platform/internal/service"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"github.com/spf13/viper"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"strings"
)

// Injectors from wire.go:

func InitComponents() (*Components, error) {
	viper, err := provideViper()
	if err != nil {
		return nil, err
	}
	db, err := provideGormDB(viper)
	if err != nil {
		return nil, err
	}
	sqlDB, err := provideSQLDB(db, viper)
	if err != nil {
		return nil, err
	}
	client := provideRedisClient(viper)
	mainGinMode := provideGinMode(viper)
	mainServerPort := provideServerPort(viper)
	mainJwtSecret := provideJWTSecret(viper)
	mainJwtExpireHours := provideJWTExpire(viper)
	mainLogChanSize := provideLogChanSizeVal(viper)
	v := provideLogChan(mainLogChanSize)
	userRepository := repository.NewUserRepository(db)
	roleRepository := repository.NewRoleRepository(db)
	permissionRepository := repository.NewPermissionRepository(db)
	tokenVersionRepository := repository.NewTokenVersionRepository(client)
	operationLogRepository := repository.NewOperationLogRepository(db)
	rateLimiter := middleware.NewRedisRateLimiter(client)
	userService := provideUserService(userRepository, tokenVersionRepository, roleRepository, mainJwtSecret, mainJwtExpireHours)
	userHandler := handler.NewUserHandler(userService)
	rolePermissionRepository := repository.NewRolePermissionRepository(db)
	roleService := service.NewRoleService(roleRepository, permissionRepository, rolePermissionRepository, userRepository)
	roleHandler := handler.NewRoleHandler(roleService)
	permissionHandler := handler.NewPermissionHandler(roleService)
	logService := service.NewLogService(operationLogRepository)
	logHandler := handler.NewLogHandler(logService)
	components := &Components{
		DB:               db,
		SQLDB:            sqlDB,
		RedisClient:      client,
		GinMode:          mainGinMode,
		ServerPort:       mainServerPort,
		JWTSecret:        mainJwtSecret,
		JWTExpire:        mainJwtExpireHours,
		LogChan:          v,
		UserRepo:         userRepository,
		RoleRepo:         roleRepository,
		PermRepo:         permissionRepository,
		TokenVersionRepo: tokenVersionRepository,
		LogRepo:          operationLogRepository,
		RateLimiter:      rateLimiter,
		UserHandler:      userHandler,
		RoleHandler:      roleHandler,
		PermHandler:      permissionHandler,
		LogHandler:       logHandler,
	}
	return components, nil
}

// wire.go:

type ginMode string

type serverPort string

type jwtSecret string

type jwtExpireHours int

type logChanSize int

func provideViper() (*viper.Viper, error) {
	v := viper.New()
	v.SetConfigName("config")
	v.SetConfigType("yaml")
	v.AddConfigPath("./config")
	if err := v.ReadInConfig(); err != nil {
		return nil, err
	}
	v.SetEnvPrefix("IAM")
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	v.AutomaticEnv()
	return v, nil
}

func provideGormDB(v *viper.Viper) (*gorm.DB, error) {
	return gorm.Open(mysql.Open(v.GetString("database.dsn")), &gorm.Config{})
}

func provideSQLDB(db *gorm.DB, v *viper.Viper) (*sql.DB, error) {
	sqlDB, err := db.DB()
	if err != nil {
		return nil, err
	}
	sqlDB.SetMaxOpenConns(v.GetInt("database.max_open_conns"))
	sqlDB.SetMaxIdleConns(v.GetInt("database.max_idle_conns"))
	return sqlDB, nil
}

func provideRedisClient(v *viper.Viper) *redis.Client {
	return redis.NewClient(&redis.Options{
		Addr:     v.GetString("redis.addr"),
		Password: v.GetString("redis.password"),
		DB:       v.GetInt("redis.db"),
	})
}

func provideGinMode(v *viper.Viper) ginMode { return ginMode(v.GetString("server.mode")) }

func provideServerPort(v *viper.Viper) serverPort { return serverPort(v.GetString("server.port")) }

func provideJWTSecret(v *viper.Viper) jwtSecret { return jwtSecret(v.GetString("jwt.secret")) }

func provideJWTExpire(v *viper.Viper) jwtExpireHours {
	return jwtExpireHours(v.GetInt("jwt.expire_hours"))
}

func provideLogChanSizeVal(v *viper.Viper) logChanSize {
	size := v.GetInt("log.channel_size")
	if size <= 0 {
		size = 1000
	}
	if size > 100000 {
		size = 100000
	}
	return logChanSize(size)
}

func provideLogChan(size logChanSize) chan model.OperationLog {
	return make(chan model.OperationLog, int(size))
}

// 包装构造函数，将具名类型转为原始类型
func provideUserService(
	userRepo repository.UserRepository,
	tokenVersionRepo repository.TokenVersionRepository,
	roleRepo repository.RoleRepository,
	secret jwtSecret,
	expire jwtExpireHours,
) service.UserService {
	return service.NewUserService(userRepo, tokenVersionRepo, roleRepo, string(secret), int(expire))
}

var infraSet = wire.NewSet(
	provideViper,
	provideGormDB,
	provideSQLDB,
	provideRedisClient,
	provideGinMode,
	provideServerPort,
	provideJWTSecret,
	provideJWTExpire,
	provideLogChanSizeVal,
	provideLogChan,
)

var repoSet = wire.NewSet(repository.NewUserRepository, repository.NewTokenVersionRepository, repository.NewPermissionRepository, repository.NewRoleRepository, repository.NewRolePermissionRepository, repository.NewOperationLogRepository)

var svcSet = wire.NewSet(
	provideUserService, service.NewRoleService, service.NewLogService,
)

var handlerSet = wire.NewSet(handler.NewUserHandler, handler.NewRoleHandler, handler.NewPermissionHandler, handler.NewLogHandler)

type Components struct {
	DB               *gorm.DB
	SQLDB            *sql.DB
	RedisClient      *redis.Client
	GinMode          ginMode
	ServerPort       serverPort
	JWTSecret        jwtSecret
	JWTExpire        jwtExpireHours
	LogChan          chan model.OperationLog
	UserRepo         repository.UserRepository
	RoleRepo         repository.RoleRepository
	PermRepo         repository.PermissionRepository
	TokenVersionRepo repository.TokenVersionRepository
	LogRepo          repository.OperationLogRepository
	RateLimiter      middleware.RateLimiter
	UserHandler      *handler.UserHandler
	RoleHandler      *handler.RoleHandler
	PermHandler      *handler.PermissionHandler
	LogHandler       *handler.LogHandler
}
